substitutions:
  _REGION: asia-northeast3
  _REPOSITORY: autoresearch-dev-docker
  _IMAGE_TAG: manual

steps:
  - id: build-airflow-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/airflow/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/autoresearch-airflow:${_IMAGE_TAG}
      - docker/airflow

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/autoresearch-airflow:${_IMAGE_TAG}
