apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: airflow-scheduler
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: airflow-scheduler
  updatePolicy:
    updateMode: "Off"
